# Generated by Django 3.0.3 on 2020-07-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=60)),
                ("city", models.TextField(max_length=60)),
                ("state", models.TextField(max_length=20)),
            ],
            options={"ordering": ["name"],},
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=60)),
                ("colleges", models.ManyToManyField(to="ksas.College")),
            ],
        ),
        migrations.CreateModel(
            name="Ksa",
            fields=[
                (
                    "id",
                    models.TextField(
                        max_length=3, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "ksa_type",
                    models.TextField(
                        choices=[("1", "knowledge"), ("2", "skill"), ("3", "ability")],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(max_length=200)),
                ("colleges", models.ManyToManyField(to="ksas.College")),
                ("jobs", models.ManyToManyField(to="ksas.Job")),
            ],
            options={"ordering": ["id"],},
        ),
    ]
